"""empty message

Revision ID: 1c5a05cb41ef
Revises: 849ce022e5ec
Create Date: 2024-11-30 13:05:00.101434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5a05cb41ef'
down_revision = '849ce022e5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('liked',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('liked',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
