"""empty message

Revision ID: 611862cbfb81
Revises: 1e9a6c79f994
Create Date: 2024-11-25 02:26:24.485154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611862cbfb81'
down_revision = '1e9a6c79f994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
