"""empty message

Revision ID: 70acfe30e86f
Revises: bea98e782b4c
Create Date: 2024-11-29 14:30:35.646622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70acfe30e86f'
down_revision = 'bea98e782b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE(),
               existing_nullable=True)

    # ### end Alembic commands ###
