"""empty message

Revision ID: 966df317e25e
Revises: 1c5a05cb41ef
Create Date: 2024-11-30 14:53:12.787678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966df317e25e'
down_revision = '1c5a05cb41ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_user_id', sa.Integer(), nullable=False),
    sa.Column('post_book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_book_id'], ['post.book_id'], ),
    sa.ForeignKeyConstraint(['post_user_id'], ['post.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_user_id', 'post_book_id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('liked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked', sa.BOOLEAN(), nullable=True))

    op.drop_table('liked')
    # ### end Alembic commands ###
